### ISSUE TITLE
need train model and aflw.sqlite

### ISSUE THREAD

**Issue by zhuhongweiyi** [takiyu/hyperface#1]
hi, thank you for sharing the code.
Could you share me with aflw.sqlite and trained model ?Because I cannot download it from the link.
my email is 1661537267@qq.com
thank you very much

**Comment by takiyu** [comment]
You can download trained model (README.md, line 51), however I cannot share `aflw.sqlite` because of the license.

I added `scripts/use_on_file.py` to test with your images. Please read README.md.

**Comment by zhuhongweiyi** [comment]
hi, thank you for replying.
Could you tell me how to get the  aflw.sqlite or the process of  aflw.sqlite?
thank you very much

**Comment by takiyu** [comment]
`aflw.sqlite` is a part of AFLW dataset and the dataset also contains face images corresponding to the sqlite file.
To download AFLW, you have to email the owner. Please read the following website.
https://lrs.icg.tugraz.at/research/aflw/
