### ISSUE TITLE
is aflw_cache.npz missing?

### ISSUE THREAD

**Issue by amnestorov** [takiyu/hyperface#6]
Hi takiyu, 
I am trying to run your implementation of Hyperface but I can't see the file "aflw_cache.npz".
Thanks.
Cheers,
Anna

**Comment by takiyu** [comment]
"aflw_cache.npz" is a cache file which contains face rectangles.
It will be created from AFLW dataset and dlib's face detection.

**Comment by amnestorov** [comment]
Oh, I got it!
Thanks
Cheers,
Anna
