### ISSUE TITLE
Error with trained model

### ISSUE THREAD

**Issue by xuehaouwa** [takiyu/hyperface#7]
Hi takiyu,

I tried to use trained model (model_epoch_190 downloaded from your link). It seems there is an error when I use `python ./scripts/use_on_file.py --model model_epoch_190 --img sample_images/lena_face.png`

I have looked into model_epoch_190. There are all .npy files in that folder. But it needs `chainer.serializers.load_npz(args.model, model)`.

Am I using the trained model in a right way? Could you tell me more details about how I can use model_epoch_190, please?

**Comment by takiyu** [comment]
I think you downloaded from Google Drive.
In Google Drive, the file `model_epoch_190` is automatically opened with `zip explorer`.
`model_epoch_190` is a zip format file, but there is no need to unzip.
